AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'
  - 'config/**/*'
  - 'db/migrate/*'
  - 'bin/**/*'
  - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false