version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.5-node'
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
  checking:
    docker:
      - image: 'cimg/ruby:2.5-node'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
  test:
    docker:
      - image: 'cimg/ruby:2.5-node'
      - environment:
          POSTGRES_DB: sweater-weather-development
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: ''
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-demo-ruby
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test
orbs:
  node: circleci/node@x.y
  ruby: circleci/ruby@x.y
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
