version: 2.1

orbs:
  heroku: circleci/heroku@1.2.0

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: gem install bundler
      # Bundle install dependencies
      # - run: bundler update --bundler
      - run: bundle config set path vendor/bundle
      # Database setup
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake
